[package]
name = "Kyun2Stop"
version = "1.2.1"
edition = "2024"

[dependencies]
nih_plug      = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git" }

[lib]
crate-type = ["cdylib", "staticlib"]

[patch."https://github.com/robbert-vdh/nih-plug.git"]
nih_plug = { path = "nih-plug-patched" }
nih_plug_egui = { path = "nih-plug-patched/nih_plug_egui" }

